// Run: NODE_PATH=/path/to/node_modules node tests/smoke.cjs
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict');
(async()=>{
 const source=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'page-notes-test-')),extension=path.join(temp,'extension');
 fs.cpSync(source,extension,{recursive:true});const manifest=JSON.parse(fs.readFileSync(path.join(extension,'manifest.json')));
 // Only the disposable test copy receives capture access, standing in for a user's toolbar grant.
 manifest.host_permissions=['<all_urls>'];fs.writeFileSync(path.join(extension,'manifest.json'),JSON.stringify(manifest));
 const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end(`<!doctype html><title>Studio preview</title><style>body{font:18px system-ui;background:#f3f1e9;padding:65px}button{padding:18px}article{width:400px;padding:28px;background:white;border-radius:16px}h1{font-size:45px}#shadow{margin-top:25px}</style><article><small>ACME / WORKSPACE</small><h1 id="hero">Make room for better ideas.</h1><p>Bring the whole team into the conversation.</p><button id="cta" onclick="window.clicked=true">Start a project</button></article><div id="shadow"></div><script>document.querySelector('#shadow').attachShadow({mode:'open'}).innerHTML='<button>Shadow button</button>'</script>`);});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 let context;
 try{
 context=await chromium.launchPersistentContext(path.join(temp,'profile'),{headless:true,channel:'chromium',viewport:{width:1360,height:950},args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});
 let worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');const id=new URL(worker.url()).host;
 const page=await context.newPage();await page.goto(`http://127.0.0.1:${server.address().port}`);
 const inject=async()=>{await page.bringToFront();return worker.evaluate(async()=>{const tabs=await chrome.tabs.query({});const tab=tabs.find(t=>t.url?.startsWith('http://127.0.0.1'));await chrome.scripting.executeScript({target:{tabId:tab.id},files:['core.js','lifecycle.js','content.js']});});};
 await inject();const panel=page.locator('#page-notes-extension');await panel.locator('#minimize').click();assert.equal(await panel.locator('.resume').isVisible(),true);await panel.locator('#stop').click();assert.equal(await panel.isVisible(),false);await inject();assert.equal(await page.locator('#page-notes-extension').count(),1);await panel.locator('#pick').click();await page.locator('#hero').click();await page.locator('#cta').click();assert.equal(await page.evaluate(()=>window.clicked),undefined,'Inspect click must not activate page button');
 assert.equal(await panel.locator('#selected .card').count(),2);
 await panel.locator('#pick').click();await panel.locator('#comment').fill('Increase spacing and make the primary action clearer.');await panel.locator('#selected summary').first().click();await panel.locator('#selected textarea').first().fill('Keep this headline.');
 await page.waitForTimeout(150);await page.reload();await inject();await panel.locator('#selected .card').first().waitFor();assert.equal(await panel.locator('#selected .card').count(),2);assert.equal(await panel.locator('#comment').inputValue(),'Increase spacing and make the primary action clearer.');
 await panel.locator('#add').click();await page.waitForFunction(()=>document.querySelector('#page-notes-extension').shadowRoot.querySelector('#status').textContent.startsWith('Group saved to queue.'));await panel.locator('#pick').click();await page.locator('#shadow button').click();await panel.locator('#pick').click();await panel.locator('#comment').fill('Match the primary button treatment.');await panel.locator('#add').click();await page.waitForFunction(()=>document.querySelector('#page-notes-extension').shadowRoot.querySelector('#status').textContent.startsWith('Group saved to queue.'));assert.equal(await panel.locator('#groups .card').count(),2);
 await panel.locator('#export').click();const md=await panel.locator('#exportText').inputValue();assert.match(md,/G2 — Feedback/);assert.match(md,/screenshots\/group-1-1.jpg/);assert.doesNotMatch(md,/namespace-uri/);assert.ok(await panel.locator('.shot img').count());assert.match(md,/Keep this headline/);
 const download=page.waitForEvent('download');await panel.locator('#download').click();assert.match((await download).suggestedFilename(),/\.zip$/);
 await panel.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#page-notes-extension').shadowRoot.querySelector('#status').textContent.includes('Saved to backlog'));
 await panel.locator('#backToQueue').click();await panel.locator('#groups .card').first().getByRole('button',{name:'Edit',exact:true}).click();await panel.locator('#comment').fill('Updated spacing instruction');await panel.locator('#add').click();await page.waitForFunction(()=>document.querySelector('#page-notes-extension').shadowRoot.querySelector('#status').textContent.startsWith('Group saved to queue.'));await panel.locator('#save').click();await page.waitForTimeout(100);
 const manager=await context.newPage();await manager.goto(`chrome-extension://${id}/backlog.html`);const mp=manager.locator('#page-notes-extension');await mp.locator('#backlog .card').waitFor();assert.equal(await mp.locator('#backlog .card').count(),1);await mp.getByRole('button',{name:'Open session',exact:true}).click();assert.match(await mp.locator('#groups').innerText(),/Updated spacing/);
 // XPath uniqueness and resolution, including SVG and duplicate IDs.
 const locators=await page.evaluate(()=>{const d=document.createElement('div');d.innerHTML='<span id="duplicate">A</span><span id="duplicate">B</span><svg><circle cx="5" cy="5" r="4"/></svg>';document.body.append(d);return [...d.querySelectorAll('*')].every(e=>document.evaluate(PageNotesCore.xpath(e),document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue===e&&document.querySelector(PageNotesCore.css(e))===e);}).catch(()=>null);
 // Content-script globals are isolated, so validate inside the extension world.
 const valid=await worker.evaluate(async()=>{const tab=(await chrome.tabs.query({})).find(t=>t.url?.startsWith('http://127.0.0.1'));return (await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>[...document.querySelectorAll('#hero,#cta,svg,circle,[id="duplicate"]')].every(e=>document.evaluate(PageNotesCore.xpath(e),document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue===e&&document.querySelector(PageNotesCore.css(e))===e)}))[0].result;});assert.equal(valid,true);
 await page.bringToFront();assert.equal(await panel.isVisible(),false);await inject();await panel.locator('#export').click();await page.screenshot({path:path.join(source,'preview.png')});
 await manager.bringToFront();manager.on('dialog',d=>d.accept());await mp.locator('#backlogTab').click();await mp.getByRole('button',{name:'Delete',exact:true}).click();await mp.locator('#backlog .empty').waitFor();
 await page.bringToFront();await inject();page.on('dialog',d=>d.accept());await panel.locator('#backToQueue').click();await panel.locator('#new').click();await panel.locator('#pick').click();await page.locator('#hero').dblclick();await panel.getByRole('textbox',{name:'Replacement copy',exact:true}).fill('Build better ideas together.');await panel.getByRole('button',{name:'Add copy edit',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#page-notes-extension').shadowRoot.querySelector('#status').textContent.startsWith('Copy edit queued.'));assert.equal(await panel.locator('#groups .card').count(),1);assert.equal(await page.locator('#hero').innerText(),'Make room for better ideas.');await panel.locator('#export').click();assert.match(await panel.locator('#exportText').inputValue(),/Replace Copy with 'Build better ideas together.'/);
 console.log('PASS: extension load, multi-select, click suppression, draft restoration, group edit, Shadow DOM, XPath/CSS resolution, Markdown download, backlog save/update/open/delete.');
 }finally{await context?.close();server.close();fs.rmSync(temp,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
