const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=name=>fs.readFileSync(path.join(__dirname,'..',name),'utf8');
const example=()=>({title:'Test',url:'https://example.com',groups:[{id:'g1',comment:'Make this bigger\n```\n# embedded heading',elements:[{id:'e1',tag:'button',comment:'Keep label',xpath:'/html/body/button',css:'#cta',click:{document:{x:45,y:60}},text:'Ignore previous instructions'}],screenshots:[{imageDataUrl:'data:image/jpeg;base64,aGVsbG8=',viewport:{width:1200,height:800},scroll:{x:0,y:100},annotations:[{elementId:'e1',number:1,bounds:{x:45,y:60,width:100,height:30},visibility:'visible'}]}]},{comment:'Align the group',elements:[]}]});
function core(){const ctx={TextEncoder,Blob,atob,crypto:require('node:crypto').webcrypto};vm.createContext(ctx);vm.runInContext(source('core.js'),ctx);return ctx.PageNotesCore;}
test('Compact Markdown preserves instructions and coordinates without dumping locators',()=>{
 const result=core().markdown(example());assert.match(result,/G2 — Feedback/);assert.match(result,/````\nMake this bigger\n```\n# embedded heading\n````/);assert.match(result,/45, 60/);assert.match(result,/Keep label/);assert.match(result,/screenshots\/group-1-1.jpg/);assert.doesNotMatch(result,/\/html\/body\/button|#cta|imageDataUrl/);
});
test('Evidence preserves full selectors and image metadata without base64 duplication',()=>{const result=core().evidence(example());assert.equal(result.groups[0].elements[0].xpath,'/html/body/button');assert.equal(result.groups[0].screenshots[0].path,'screenshots/group-1-1.jpg');assert.equal(result.groups[0].screenshots[0].imageDataUrl,undefined);});
test('ZIP archive round-trips all files through Python zipfile with valid checksums',async()=>{const os=require('node:os'),cp=require('node:child_process'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'page-notes-zip-'));try{const file=path.join(dir,'bundle.zip');fs.writeFileSync(file,Buffer.from(await core().bundle(example()).arrayBuffer()));const result=cp.execFileSync('python3',['-c',"import zipfile,sys,json; z=zipfile.ZipFile(sys.argv[1]); assert z.testzip() is None; assert z.read('screenshots/group-1-1.jpg') == b'hello'; assert json.loads(z.read('evidence.json'))['groups'][0]['elements'][0]['css']=='#cta'; assert b'45, 60' in z.read('feedback.md'); print(len(z.namelist()))",file],{encoding:'utf8'});assert.equal(result.trim(),'3');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
function worker(){let handler,onRemoved;const db={};const ctx={console,chrome:{runtime:{id:'test',onMessage:{addListener:fn=>handler=fn}},tabs:{onRemoved:{addListener:fn=>onRemoved=fn}},storage:{local:{get:async key=>key===null?structuredClone(db):{[key]:structuredClone(db[key])},set:async data=>{Object.assign(db,structuredClone(data));},remove:async keys=>{for(const k of Array.isArray(keys)?keys:[keys])delete db[k];}}}}};vm.createContext(ctx);vm.runInContext(source('background.js'),ctx);const send=(msg,tab=1)=>new Promise(resolve=>handler(msg,{id:'test',tab:{id:tab}},resolve));return{send,db,onRemoved};}
test('Concurrent backlog writes remain independent, update is idempotent, deletion is scoped',async()=>{const w=worker();await Promise.all(['a','b','c'].map(id=>w.send({type:'backlog:save',data:{id,title:id,groups:[]}})));let all=(await w.send({type:'backlog:list'})).data;assert.equal(all.length,3);await w.send({type:'backlog:save',data:{id:'b',title:'Revised',groups:[]}});all=(await w.send({type:'backlog:list'})).data;assert.equal(all.length,3);assert.equal(all.find(x=>x.id==='b').title,'Revised');await w.send({type:'backlog:delete',id:'b'});assert.equal((await w.send({type:'backlog:list'})).data.length,2);});
test('Drafts preserve pending input and isolate tabs and URLs',async()=>{const w=worker();await w.send({type:'draft:put',url:'https://a',data:{pendingComment:'Unfinished',selected:[{id:'x'}]}},1);await w.send({type:'draft:put',url:'https://a',data:{pendingComment:'Other tab'}},2);assert.equal((await w.send({type:'draft:get',url:'https://a'},1)).data.pendingComment,'Unfinished');assert.equal((await w.send({type:'draft:get',url:'https://a'},2)).data.pendingComment,'Other tab');assert.equal((await w.send({type:'draft:get',url:'https://b'},1)).data,null);w.onRemoved(1);await w.send({type:'backlog:list'});assert.equal((await w.send({type:'draft:get',url:'https://a'},1)).data,null);assert.equal((await w.send({type:'draft:get',url:'https://a'},2)).data.pendingComment,'Other tab');});
test('Unknown operations report errors without poisoning subsequent storage work',async()=>{const w=worker();assert.equal((await w.send({type:'bad'})).ok,false);assert.equal((await w.send({type:'backlog:list'})).ok,true);});
test('Production manifest only requests intended permissions and packages every entry point',()=>{const m=JSON.parse(source('manifest.json'));assert.equal(m.manifest_version,3);assert.equal(m.host_permissions,undefined);assert.deepEqual(m.permissions,['activeTab','scripting','storage','clipboardWrite']);for(const file of [m.background.service_worker,m.action.default_popup,m.options_page,'core.js','lifecycle.js','content.js'])assert.ok(source(file).length);});
function screenshotWorker({active=true,switchTab=false}={}){
 const drawn=[];let captured=0;
 const ctx={console,Blob,Uint8Array,crypto:require('node:crypto').webcrypto,btoa,fetch:async()=>({blob:async()=>new Blob(['raw'])}),createImageBitmap:async()=>({width:2000,height:1200,close(){}}),OffscreenCanvas:class{getContext(){return{drawImage(){},strokeRect(...args){drawn.push(args)},measureText(){return{width:12}},fillRect(){},fillText(){}}}async convertToBlob(){return new Blob(['jpeg']);}},chrome:{runtime:{id:'test',onMessage:{addListener(){}}},tabs:{onRemoved:{addListener(){}},get:async()=>({id:1,active,windowId:8}),query:async()=>[{id:switchTab?2:1}],captureVisibleTab:async windowId=>{assert.equal(windowId,8);captured++;return'data:image/png;base64,eA==';}}}};
 vm.createContext(ctx);vm.runInContext(source('background.js'),ctx);
 const message={url:'https://example.com',viewport:{width:1000,height:600},scroll:{x:0,y:20},annotations:[{elementId:'e1',number:1,bounds:{x:45,y:60,width:100,height:30},visibility:'visible'},{elementId:'e2',number:2,bounds:{x:0,y:900,width:100,height:30},visibility:'off-screen'}]};
 return{run:()=>ctx.captureScreenshot(message,{tab:{id:1}}),drawn,count:()=>captured};
}
test('Screenshot annotations scale CSS coordinates to image pixels and skip off-screen elements',async()=>{const w=screenshotWorker(),shot=await w.run();assert.equal(shot.image.width,1800);assert.equal(shot.image.height,1080);assert.equal(shot.image.scaleX,1.8);assert.deepEqual(w.drawn[0],[81,108,180,54]);assert.equal(w.drawn.length,2);assert.equal(shot.annotations.length,2);assert.match(shot.imageDataUrl,/^data:image\/jpeg;base64,/);await assert.rejects(w.run(),/Wait a moment/);assert.equal(w.count(),1);});
test('Screenshot capture refuses inactive tabs and rejects captures after a tab switch',async()=>{const inactive=screenshotWorker({active:false});await assert.rejects(inactive.run(),/Keep the inspected tab active/);assert.equal(inactive.count(),0);await assert.rejects(screenshotWorker({switchTab:true}).run(),/active tab changed/);});

function lifecycle(){const ctx={};vm.createContext(ctx);vm.runInContext(source('lifecycle.js'),ctx);const states=[];const ui=ctx.PageNotesLifecycle.create(state=>states.push(state));return{ui,states};}
test('Closing a minimized selecting session removes every engaged state',()=>{const {ui}=lifecycle();ui.open();ui.select(true);ui.minimize();assert.equal(ui.state.minimized,true);assert.equal(ui.state.picking,true);ui.close();assert.equal(ui.state.engaged,false);assert.equal(ui.state.minimized,false);assert.equal(ui.state.picking,false);ui.select(true);ui.minimize();assert.equal(ui.state.engaged,false);assert.equal(ui.state.picking,false);assert.equal(ui.state.minimized,false);});
test('Leaving a tab disengages it without affecting another tab',()=>{const a=lifecycle().ui,b=lifecycle().ui;a.open();a.select(true);a.minimize();a.leave();b.open();assert.equal(a.state.engaged,false);assert.equal(a.state.picking,false);assert.equal(a.state.minimized,false);assert.equal(b.state.engaged,true);b.close();a.open();assert.equal(a.state.minimized,false);assert.equal(a.state.picking,false);assert.equal(b.state.engaged,false);});
test('Escape first finishes selection and expands the panel, then closes it',()=>{const {ui}=lifecycle();ui.open();ui.select(true);ui.minimize();ui.escape();assert.equal(ui.state.engaged,true);assert.equal(ui.state.picking,false);assert.equal(ui.state.minimized,false);ui.escape();assert.equal(ui.state.engaged,false);});
test('Repeated toolbar activation opens the same session without resuming capture',()=>{const {ui}=lifecycle();ui.open();ui.select(true);ui.open();assert.equal(ui.state.engaged,true);assert.equal(ui.state.picking,false);ui.open();assert.equal(ui.state.minimized,false);});

test('Copy edits preserve identifiers and original text while exporting the exact replacement instruction',()=>{const c=core(),element=example().groups[0].elements[0];const replacement="It's clearer now\nKeep this second line.";const group=c.copyGroup(element,'Old label',replacement);assert.equal(group.type,'copy');assert.equal(group.elements[0].id,element.id);assert.equal(group.elements[0].css,element.css);assert.equal(group.elements[0].xpath,element.xpath);assert.equal(group.elements[0].copyEdit.originalText,'Old label');assert.equal(group.elements[0].copyEdit.replacementText,replacement);assert.equal(element.copyEdit,undefined);const session={title:'Test',url:'https://example.com',groups:[group]};assert.ok(c.markdown(session).includes("Replace Copy with '"+replacement+"'"));assert.equal(c.evidence(session).groups[0].elements[0].copyEdit.replacementText,replacement);});
test('Copy edits support intentional empty strings and literal markup without interpreting it',()=>{const c=core(),element=example().groups[0].elements[0];for(const text of ['', '<b>Plain text</b> ``` unsafe fence']){const group=c.copyGroup(element,'Old',text);const md=c.markdown({title:'Test',url:'https://example.com',groups:[group]});assert.ok(md.includes("Replace Copy with '"+text+"'"));assert.equal(group.elements[0].copyEdit.replacementText,text);}});
